### ISSUE TITLE
来自山西应急管理厅的消息 山西近期严重洪涝灾害导致全省11个市76个县（市、区）175.71万人受灾 山西近期严重洪涝灾

### ISSUE THREAD

**Issue by Functional-Account** [hailiang-wang/issues#7]
Labels: 文档， 创建者: 王海良@Chatopera
# 描述

来自 Chatopera测试群1 （微信群或私聊）对话记录

`王海良@Chatopera`: 帮助  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 11:22:15)*
`王海良@Chatopera`: 你好  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 11:22:52)*
`王海良@Chatopera`: 延迟这么大  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 11:23:30)*
`王海良@Chatopera`: 你好  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 11:23:51)*
`波特`: 你好！我是开源社机器人助手 OSSChat  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 11:23:54)*
`王海良@Chatopera`: 你好  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 14:21:41)*
`王海良@Chatopera`: 你好  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 14:21:42)*
`OSSChat`: 你好！我是开源社机器人助手 OSSChat  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 14:21:44)*
`波特`: 你好！我是开源社机器人助手 OSSChat  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 14:21:44)*
`王海良@Chatopera`: 帮助  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 14:21:48)*
`王海良@Chatopera`: 帮助  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 14:21:50)*
`波特`: 机器人助手有如下技能:
  1. 自动创建 Issue - "以上创建 Issue", "以上10条创建 Issue", "以上10条创建工单"  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 14:21:51)*
`OSSChat`: 机器人助手有如下技能  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 14:21:52)*
`王海良@Chatopera`: 帮助  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 14:22:08)*
`王海良@Chatopera`: 我们的共同家园  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 14:22:28)*
`王海良@Chatopera`: 生物多样性保护  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 14:22:34)*
`王海良@Chatopera`: 山西、陕西两地加紧防汛救灾  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 14:22:53)*
`王海良@Chatopera`: 来自山西应急管理厅的消息：山西近期严重洪涝灾害导致全省11个市76个县（市、区）175.71万人受灾，12.01万人紧急转移安置，284.96万亩农作物受灾，1.7万余间房屋倒塌。  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 14:23:01)*
`王海良@Chatopera`: 创建工单  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 14:23:09)*
`王海良@Chatopera`: 应急管理厅的消息：山西近期严重洪涝灾害导致全省11个市76个  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; *(2021-10-12 15:11:07)*

---
提示：以上为未整理的聊天历史，更多介绍查看评论信息。
<div align="right">:speech_balloon: Opened by <a href="https://github.com/kaiyuanshe/osschat">OSSChat</a> automatically.</div>

**Comment by hailiang-wang** [comment]
测试
